### ISSUE TITLE
add conda recipe 

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#32]

**Comment by rekado** [comment]
Is this still needed?

**Comment by katwre** [comment]
My conda file looks like this and it worked for me on the BIH cluster. I can include it, but I am not sure yet what to do with the `~/.condarc` file, so just write in README that it has to be created by users by themselves, right?
```
# This file may be used to create an environment using:
# $ conda create --name bsseq_pigx --file <this file> 
## make sure to have the following conda channels in ~/.condarc file
# https://bioconda.github.io/#set-up-channels
## install R with conda 
# https://conda.io/docs/user-guide/tasks/use-r-with-conda.html#using-r-with-conda
#channels:
#  - anaconda-fusion
#  - defaults
#  - bioconda
#  - r
#  - pypi
#  - conda-forge

snakemake=4.0.0
fastqc=0.11.4 #0.11.5 is the newest, but has a bug
trim-galore=0.4.3
python=3.5.4
cutadapt
samtools
bowtie
bismark
pyyaml
pandoc

#additional requirements for R libraries:
r-essentials
r-rmarkdown
r-bookdown
bioconductor-rtracklayer
r-DT
bioconductor-ggbio
bioconductor-annotationhub
bioconductor-genomation
bioconductor-genomeinfodb
bioconductor-methylkit
bioconductor-rtracklayer
```

**Comment by rekado** [comment]
I suppose we could also simply generate it from the Guix package definition.

**Comment by rekado** [comment]
I haven't tested this much, but here's a draft:

```scheme
(use-modules (gnu)
             (guix)
             (guix base32)
             (guix licenses)
             (srfi srfi-1)
             (ice-9 match))

(define package
  (specification->package "pigx-bsseq"))

(define (bioconductor-package? package)
  "Return true if PACKAGE is an R package from Bioconductor."
  (let ((predicate (lambda (uri)
                     (string-prefix? "https://bioconductor.org" uri))))
    (and (string-prefix? "r-" (package-name package))
         (predicate (match
                        (origin-uri (package-source package))
                      ((first . rest) first)
                      (it it))))))

(define (name->conda-name package)
  (cond
   ((bioconductor-package? package)
    (string-append "bioconductor"
                   (string-drop (package-name package) 1)))
   (else (package-name package))))

(define* (emit-meta package #:optional (port (current-output-port)))
  (define meta
    `((package
       (name ,(package-name package))
       (version ,(package-version package)))
      (source
       (url ,(origin-uri (package-source package)))
       (sha256
        ,(bytevector->base32-string
          (content-hash-value
           (origin-hash (package-source package))))))
      (build
       (script "./configure --prefix=$PREFIX && make install"))
      (requirements
       (run
        ,(list->vector
          (map (compose name->conda-name second) (package-inputs package)))))
      (about
       (home ,(package-home-page package))
       (license ,(license-name (package-license package)))
       (summary ,(package-synopsis package)))))
  (define* (print thing #:optional (indent 0))
    (let ((indentation (make-string indent #\space)))
      (display indentation port)
      (match thing
        ((label (? string? s))
         (format port "~a: ~a~%" label s))
        ((label (? vector? v))
         (format port "~a:~%" label)
         (for-each (lambda (item)
                     (format port "~a  - ~a~%" indentation item))
                   (vector->list v)))
        ((label . rest)
         (format port "~a:~%" label)
         (for-each (lambda (item) (print item (+ 2 indent)))
                   rest)))))
  (for-each print meta))

(emit-meta package)
```

Running this through Guile produces this:

```
package:
  name: pigx-bsseq
  version: 0.0.10
source:
  url: https://github.com/BIMSBbioinfo/pigx_bsseq/releases/download/v0.0.10/pigx_bsseq-0.0.10.tar.gz
  sha256: d3zbnulnbulumk4klqjiaodq74d37vqykls2ygcfha3ifz7ge5iq
build:
  script: ./configure --prefix=$PREFIX && make install
requirements:
  run:
    - coreutils
    - sed
    - grep
    - r-minimal
    - bioconductor-annotationhub
    - r-dt
    - bioconductor-genomation
    - bioconductor-methylkit
    - bioconductor-rtracklayer
    - r-rmarkdown
    - r-bookdown
    - r-ggplot2
    - bioconductor-ggbio
    - ghc-pandoc
    - ghc-pandoc-citeproc
    - python-wrapper
    - python-pyyaml
    - snakemake
    - bismark
    - fastqc
    - bowtie
    - trim-galore
    - cutadapt
    - samtools
about:
  home: http://bioinformatics.mdc-berlin.de/pigx/
  license: GPL 3+
  summary: Bisulfite sequencing pipeline from fastq to methylation reports
```
