### ISSUE TITLE
Right now only one round of diffmeth is incorporated into the report

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#77]
Right now only one round of diffmeth is incorporated into the report

**Comment by rekado** [comment]
Groups have to be specified as arrays.  In YAML that's done like this:

```
  differential-methylation:
    cores: 20
    treatment-groups:
      - ['0', '1']
      - ['0', '2']
    annotation:
...
```
An alternative is to use JSON syntax (which we already do for the groups themselves), i.e. square brackets for arrays/lists.
