### ISSUE TITLE
cluster jobs are always sent to queue "all"

### ISSUE THREAD

**Issue by katwre** [BIMSBbioinfo/pigx_bsseq#93]
I tried with a queue called 'medium' on the bih cluster and it doesnt seem to work, it always sent jobs to 'all'

```
execution:
  submit-to-cluster: yes
  jobs: 10
  nice: 19
  cluster:
    memory: 5G
    stack: 128M
    queue: medium
    contact-email: katwre@gmail.com
```
